# Generated by Django 4.0.2 on 2022-02-21 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0002_remove_super_super_type_super_super_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super',
            old_name='super_types',
            new_name='super_type',
        ),
    ]
